### ISSUE TITLE
tua-mp-service serve 拷贝project.config.json 到dist目录  看法

### ISSUE THREAD

**Issue by andypinet** [tuateam/tua-mp-service#9]
目前看来如果我把project.config.json 放在根目录下  并设置miniprogramRoot为dist后 
此时拷贝project.config.json至dist目录下 会导致预览时错误

如果用户在project.config.json设置了miniprogramRoot 就不需要再拷贝

**Comment by BuptStEve** [comment]
新版应该已经改了呀...?
